---
abstract: 'Parse Org documents'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Exception: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Org-Parser
requires:
  DateTime: 0
  DateTime::Event::Recurrence: 0
  File::Slurp: 0
  Log::Any: 0
  Module::List: 0
  Moo: 0
  String::Escape: 0
  experimental: 0
  perl: 5.010001
resources: {}
version: 0.37
