---
abstract: 'Parse Org documents'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Test::Exception: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Org-Parser
requires:
  DateTime: 0
  DateTime::Event::Recurrence: 0
  File::Slurp: 0
  Log::Any: 0
  Module::List: 0
  Moo: 0
  String::Escape: 0
  experimental: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Org-Parser/
  repository: http://github.com/sharyanto/perl-Org-Parser
version: 0.36
